-- PERGUNTAS EXTRAS QUE PODEMOS EXTRAIR RESULTADOS IMPORTANTES DO BANCO DE DADOS
-- Quais são os facilitadores que estão em mais de uma turma?
SELECT
	FCL.ID_FACILITADOR,
	FCL.NOME_FACILITADOR,
	COUNT(DISTINCT(RSL.TURMA_ID))
FROM FACILITADOR FCL
RIGHT JOIN
	RESILIA RSL
ON FCL.ID_FACILITADOR = RSL.FACILITADOR_ID
RIGHT JOIN
	TURMA TRM
ON RSL.TURMA_ID = TRM.ID_TURMA
GROUP BY FCL.ID_FACILITADOR
ORDER BY COUNT(RSL.TURMA_ID) DESC


-- Quais são os cursos mais populares com base no número de alunos matriculados?
SELECT
	CRS.NOME_CURSO AS "CURSO",
	COUNT(DISTINCT(ESTUDANTE_ID)) AS "QTD ALUNOS",
	CASE
		WHEN COUNT(DISTINCT(ESTUDANTE_ID)) >= 10 THEN 'MUITO POPULAR'
		WHEN COUNT(DISTINCT(ESTUDANTE_ID)) > 6 THEN 'MEDIANO'
		ELSE 'POUCO POPULAR'
	END AS "POPULARIDADE"
FROM
	CURSO CRS
LEFT JOIN
	RESILIA RSL
ON CRS.ID_CURSO = RSL.CURSO_ID
GROUP BY CRS.NOME_CURSO
ORDER BY COUNT(DISTINCT(ESTUDANTE_ID)) DESC


-- Quais são os alunos que estão matriculados em mais de uma turma?
SELECT
	EST.ID_ESTUDANTE,
	EST.NOME_ESTUDANTE,
	COUNT(DISTINCT(TRM.NOME_TURMA)) AS "QTD TURMAS"
FROM ESTUDANTE EST
LEFT JOIN
	RESILIA RSL
ON EST.ID_ESTUDANTE = RSL.ESTUDANTE_ID
LEFT JOIN
	TURMA TRM
ON RSL.TURMA_ID = TRM.ID_TURMA
GROUP BY EST.ID_ESTUDANTE
ORDER BY COUNT(DISTINCT(TRM.NOME_TURMA)) DESC