
INSERT INTO estudante (nome_estudante, data_nascimento, email_aluno, endereco_estudante, telefone_estudante, cpf_estudante, status)
VALUES
  ('João Silva', '1995-02-10', 'joao.silva@example.com', 'Rua A, 123', '(11) 987654321', '123.456.789-01', 'ativo'),
  ('Maria Souza', '1998-06-15', 'maria.souza@example.com', 'Rua B, 456', '(22) 99998888', '987.654.321-09', 'ativo'),
  ('Pedro Santos', '1993-09-20', 'pedro.santos@example.com', 'Rua C, 789', '(33) 77776666', '456.789.123-45', 'ativo'),
  ('Ana Oliveira', '1997-11-05', 'ana.oliveira@example.com', 'Rua D, 321', '(44) 55554444', '321.654.987-78', 'ativo'),
  ('Lucas Pereira', '1996-04-18', 'lucas.pereira@example.com', 'Rua E, 654', '(55) 22223333', '654.987.321-96', 'inativo'),
  ('Isabela Rodrigues', '1999-07-23', 'isabela.rodrigues@example.com', 'Rua F, 987', '(66) 11112222', '988.321.654-03', 'ativo'),
  ('Rafaela Almeida', '1994-01-30', 'rafaela.almeida@example.com', 'Rua G, 234', '(77) 88889999', '858.963.741-25', 'inativo'),
  ('Thiago Gomes', '1997-05-06', 'thiago.gomes@example.com', 'Rua H, 567', '(88) 33332222', '369.258.147-36', 'ativo'),
  ('Carolina Costa', '1995-08-11', 'carolina.costa@example.com', 'Rua I, 890', '(99) 44445555', '753.951.852-12', 'ativo'),
  ('Eduardo Barbosa', '1992-03-24', 'eduardo.barbosa@example.com', 'Rua J, 432', '(00) 66667777', '159.357.852-46', 'ativo'),
  ('Juliana Santos', '1996-07-09', 'juliana.santos@example.com', 'Rua K, 765', '(11) 12341234', '963.852.741-89', 'ativo'),
  ('Marcelo Lima', '1999-10-14', 'marcelo.lima@example.com', 'Rua L, 987', '(22) 56785678', '789.654.321-07', 'ativo'),
  ('Gabriela Ferreira', '1993-01-19', 'gabriela.ferreira@example.com', 'Rua M, 210', '(33) 90129012', '357.951.852-30', 'ativo'),
  ('Matheus Oliveira', '1998-05-04', 'matheus.oliveira@example.com', 'Rua N, 543', '(44) 34563456', '857.741.963-24', 'inativo'),
  ('Beatriz Rodrigues', '1994-09-17', 'beatriz.rodrigues@example.com', 'Rua O, 876', '(55) 78907890', '654.321.987-58', 'ativo'),
  ('Anderson Silva', '1997-12-02', 'anderson.silva@example.com', 'Rua P, 109', '(66) 23452345', '321.654.987-62', 'ativo'),
  ('Laura Almeida', '1995-02-07', 'laura.almeida@example.com', 'Rua Q, 543', '(77) 56785678', '989.321.654-81', 'inativo'),
  ('Vinicius Gomes', '1998-06-12', 'vinicius.gomes@example.com', 'Rua R, 987', '(88) 90129012', '789.654.321-06', 'ativo'),
  ('Camila Costa', '1993-09-27', 'camila.costa@example.com', 'Rua S, 321', '(99) 34563456', '654.987.321-98', 'ativo'),
  ('Rafael Barbosa', '1996-11-10', 'rafael.barbosa@example.com', 'Rua T, 654', '(00) 78907890', '985.654.321-14', 'ativo'),
  ('Fernanda Santos', '1999-03-23', 'fernanda.santos@example.com', 'Rua U, 210', '(11) 23452345', '321.987.654-03', 'ativo'),
  ('Guilherme Lima', '1994-06-28', 'guilherme.lima@example.com', 'Rua V, 543', '(22) 56785678', '654.321.987-25', 'ativo'),
  ('Larissa Ferreira', '1997-10-03', 'larissa.ferreira@example.com', 'Rua W, 876', '(33) 90129012', '983.654.321-36', 'ativo'),
  ('Renato Oliveira', '1993-01-18', 'renato.oliveira@example.com', 'Rua X, 109', '(44) 34563456', '320.987.654-40', 'ativo'),
  ('Júlia Rodrigues', '1998-05-01', 'julia.rodrigues@example.com', 'Rua Y, 432', '(55) 78907890', '654.321.987-66', 'inativo'),
  ('Gustavo Silva', '1994-09-14', 'gustavo.silva@example.com', 'Rua Z, 765', '(66) 23452345', '982.654.321-32', 'ativo'),
  ('Sofia Almeida', '1996-12-29', 'sofia.almeida@example.com', 'Rua AA, 210', '(77) 56785678', '327.987.654-53', 'inativo'),
  ('Lucas Gomes', '1999-04-04', 'lucas.gomes@example.com', 'Rua BB, 543', '(88) 90129012', '746.852.963-25', 'ativo'),
  ('Manuela Costa', '1995-08-09', 'manuela.costa@example.com', 'Rua CC, 876', '(99) 34563456', '981.654.321-69', 'ativo'),
  ('Felipe Barbosa', '1992-12-22', 'felipe.barbosa@example.com', 'Rua DD, 109', '(00) 78907890', '321.987.654-84', 'inativo'),
  ('Amanda Lima', '1996-03-15', 'amanda.lima@example.com', 'Rua EE, 432', '(11) 23452345', '654.987.321-24', 'ativo'),
  ('Pedro Henrique', '1999-07-20', 'pedro.henrique@example.com', 'Rua FF, 765', '(22) 56785678', '980.321.654-36', 'inativo'),
  ('Mariana Fernandes', '1994-11-25', 'mariana.fernandes@example.com', 'Rua GG, 987', '(33) 90129012', '369.852.741-58', 'ativo'),
  ('Ricardo Santos', '1997-04-30', 'ricardo.santos@example.com', 'Rua HH, 210', '(44) 34563456', '856.963.741-60', 'ativo'),
  ('Aline Oliveira', '1993-09-05', 'aline.oliveira@example.com', 'Rua II, 543', '(55) 78907890', '747.852.963-88', 'inativo'),
  ('Daniel Rodrigues', '1998-01-10', 'daniel.rodrigues@example.com', 'Rua JJ, 876', '(66) 23452345', '963.741.852-96', 'ativo'),
  ('Laura Alves', '1995-05-15', 'laura.alves@example.com', 'Rua KK, 109', '(77) 56785678', '859.963.741-03', 'inativo'),
  ('Vitor Gomes', '1998-09-20', 'vitor.gomes@example.com', 'Rua LL, 432', '(88) 90129012', '746.852.963-24', 'ativo'),
  ('Renata Costa', '1993-12-25', 'renata.costa@example.com', 'Rua MM, 765', '(99) 34563456', '963.741.852-40', 'ativo'),
  ('Caio Barbosa', '1996-03-01', 'caio.barbosa@example.com', 'Rua NN, 210', '(00) 78907890', '745.852.963-66', 'inativo'),
  ('Carla Santos', '1999-07-06', 'carla.santos@example.com', 'Rua OO, 543', '(11) 23452345', '853.963.741-81', 'ativo'),
  ('Rafaela Lima', '1994-11-11', 'rafaela.lima@example.com', 'Rua PP, 876', '(22) 56785678', '743.852.963-06', 'inativo'),
  ('Guilherme Ferreira', '1997-04-16', 'guilherme.ferreira@example.com', 'Rua QQ, 109', '(33) 90129012', '963.741.852-98', 'ativo'),
  ('Julia Oliveira', '1995-08-21', 'julia.oliveira@example.com', 'Rua RR, 432', '(44) 34563456', '850.963.741-40', 'ativo'),
  ('Rodrigo Rodrigues', '1998-01-26', 'rodrigo.rodrigues@example.com', 'Rua SS, 765', '(55) 78907890', '744.852.963-69', 'inativo'),
  ('Larissa Almeida', '1993-06-03', 'larissa.almeida@example.com', 'Rua TT, 210', '(66) 23452345', '963.741.852-14', 'ativo'),
  ('Leonardo Gomes', '1996-10-08', 'leonardo.gomes@example.com', 'Rua UU, 543', '(77) 56785678', '742.852.963-32', 'ativo'),
  ('Bianca Costa', '1999-02-13', 'bianca.costa@example.com', 'Rua VV, 876', '(88) 90129012', '963.741.852-53', 'inativo'),
  ('Diego Barbosa', '1994-06-18', 'diego.barbosa@example.com', 'Rua WW, 109', '(99) 34563456', '741.852.963-69', 'ativo'),
  ('Isadora Santos', '1997-10-23', 'isadora.santos@example.com', 'Rua XX, 432', '(00) 78907890', '852.963.741-84', 'ativo');


INSERT INTO facilitador ( nome_facilitador, email_facilitador, data_nascimento, endereco_facilitador, cpf_facilitador)
VALUES
  ( 'Fernando Oliveira', 'fernando.oliveira@example.com', '1980-05-12', 'Rua A, 123', '223.456.789-99'),
  ( 'Carolina Silva', 'carolina.silva@example.com', '1985-09-20', 'Rua B, 456', '987.654.321-09'),
  ( 'Rodrigo Souza', 'rodrigo.souza@example.com', '1977-03-15', 'Rua C, 789', '456.789.123-45'),
  ( 'Lúcia Santos', 'lucia.santos@example.com', '1982-07-29', 'Rua D, 321', '321.654.987-78'),
  ( 'Juliana Pereira', 'juliana.pereira@example.com', '1979-12-03', 'Rua E, 654', '654.987.321-96'),
  ( 'Ricardo Almeida', 'ricardo.almeida@example.com', '1988-06-25', 'Rua F, 987', '987.321.654-03'),
  ('Amanda Gomes', 'amanda.gomes@example.com', '1984-01-08', 'Rua G, 234', '852.963.741-25'),
  ( 'Fernanda Costa', 'fernanda.costa@example.com', '1981-04-16', 'Rua H, 567', '369.258.147-36'),
  ( 'Pedro Barbosa', 'pedro.barbosa@example.com', '1983-08-22', 'Rua I, 890', '753.951.852-12'),
  ( 'Camila Oliveira', 'camila.oliveira@example.com', '1978-02-28', 'Rua J, 432', '159.357.852-46'),
  ( 'Gustavo Santos', 'gustavo.santos@example.com', '1986-07-05', 'Rua K, 765', '963.852.741-89'),
  ( 'Larissa Lima', 'larissa.lima@example.com', '1989-11-11', 'Rua L, 987', '789.654.321-07'),
  ( 'Rafaela Ferreira', 'rafaela.ferreira@example.com', '1975-06-14', 'Rua M, 210', '357.951.852-30'),
  ( 'Vinicius Oliveira', 'vinicius.oliveira@example.com', '1980-09-27', 'Rua N, 543', '852.741.963-24'),
  ( 'Mariana Rodrigues', 'mariana.rodrigues@example.com', '1977-01-01', 'Rua O, 876', '654.321.987-58');

INSERT INTO curso ( nome_curso, descricao_curso, duracao_curso, data_inicio, data_fim)
VALUES
  ( 'Programação', 'Um curso introdutório de programação', 96, '2023-01-10', '2023-02-07'),
  ( 'Design Gráfico', 'Aprenda os fundamentos do design gráfico', 144, '2023-03-15', '2023-04-25'),
  ( 'Data Analytics', 'Aprenda a arte de analisar dados', 96, '2023-10-02', '2023-10-30'),
  ( 'Gestão de Projetos', 'Domine as melhores práticas de gerenciamento de projetos', 240, '2023-11-06', '2024-01-15'),
  ( 'Desenvolvimento Web', 'Aprenda a fazer sites íncriveis', 192, '2024-02-01', '2024-03-28'),
  ( 'Desenvolvimento FullStack', 'Domine tanto o front quanto o back end', 144, '2024-04-04', '2024-05-15'),
  ( 'Desenvolvimento Mobile', 'Aprenda a fazer aplicativos mobile', 96, '2024-06-01', '2024-06-28');

INSERT INTO modulo ( nome_modulo, descricao_modulo, carga_horaria, data_inicio, data_fim)
VALUES
  ( 'Introdução à Programação', 'Fundamentos básicos de programação', 40, '2023-01-10', '2023-02-10'),
  ( 'Design Gráfico para Iniciantes', 'Introdução aos princípios do design gráfico', 30, '2023-03-15', '2023-04-15'),
  ( 'Análise de Dados basico', 'Explorando técnicas de análise de dados', 60, '2023-05-02', '2023-06-30'),
  ( 'Gestão de Projetos Avançada', 'Melhores práticas em gerenciamento de projetos', 50, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento Web Fundamentos', 'Construindo aplicações web do zero', 80, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento FullStack', 'Aprenda a criar aplicativos completos', 90, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento Mobile com React Native', 'Criação de aplicativos móveis multiplataforma', 70, '2023-11-06', '2024-01-05'),
  ( 'Programação intermediaria', 'Fundamentos intermediario de programação', 40, '2023-01-10', '2023-02-10'),
  ( 'Design Gráfico intermediario', 'Introdução aos princípios do design gráfico', 30, '2023-03-15', '2023-04-15'),
  ( 'Análise de Dados intermediario', 'Explorando técnicas de análise de dados', 60, '2023-05-02', '2023-06-30'),
  ( 'Desenvolvimento Front-End Avançado', 'Aprofunde-se no desenvolvimento front-end', 70, '2023-11-06', '2024-01-05'),
  ( 'Design de Interfaces', 'Crie interfaces atraentes e intuitivas', 40, '2023-03-15', '2023-04-15'),
  ( 'Estatística para Análise de Dados', 'Princípios estatísticos aplicados à análise de dados', 50, '2023-05-02', '2023-06-30'),
  ( 'Gestão Ágil de Projetos', 'Utilize metodologias ágeis para o gerenciamento de projetos', 60, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento Back-End', 'Aprenda a criar e integrar sistemas back-end', 80, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento de APIs', 'Criação e consumo de APIs para integração de sistemas', 50, '2023-11-06', '2024-01-05'),
  ( 'Desenvolvimento Mobile com Flutter', 'Construção de aplicativos móveis com Flutter', 70, '2023-11-06', '2024-01-05'),
  ( 'Programação avançado', 'Fundamentos avançados de programação', 40, '2023-01-10', '2023-02-10'),
  ( 'Design Gráfico avançado', 'Introdução aos princípios do design gráfico', 30, '2023-03-15', '2023-04-15'),
  ( 'Análise de Dados avaçado', 'Explorando técnicas de análise de dados', 60, '2023-05-02', '2023-06-30');

INSERT INTO turma (nome_turma, ano_turma, quantidade_alunos)
VALUES
  ('Turma A', 2019, 30),
  ( 'Turma B', 2019, 32),
  ( 'Turma C', 2019, 31),
  ( 'Turma D', 2019, 35),
  ( 'Turma E', 2020, 25),
  ( 'Turma F', 2020, 29),
  ( 'Turma G', 2021, 28),
  ( 'Turma H', 2021, 28),
  ( 'Turma I', 2021, 26),
  ( 'Turma J', 2022, 27),
  ( 'Turma K', 2022, 30),
  ( 'Turma L', 2022, 33),
  ( 'Turma M', 2023, 26),
  ( 'Turma N', 2023, 29),
  ( 'Turma O', 2023, 30);
  
INSERT INTO resilia (estudante_id, turma_id, modulo_id, curso_id, facilitador_id, data_registro)
VALUES
    ( 34, 8, 10, 2, 15, '2022-09-18'),
    (23, 4, 19, 7, 14, '2019-07-04'),
    ( 12, 6, 15, 1, 13, '2023-06-30'),
    (17, 13, 8, 5, 1, '2022-05-21'),
    ( 9, 7, 3, 7, 1, '2020-03-08'),
    (40, 12, 4, 2, 5, '2019-08-14'),
    (19, 3, 18, 6, 9, '2021-11-09'),
    (31, 6, 14, 5, 2, '2021-02-01'),
    (5, 11, 6, 7, 3, '2019-09-22'),
    (47, 15, 7, 4, 4, '2020-06-17'),
    (13, 7, 20, 2, 5, '2022-02-11'),
    (8, 14, 4, 3, 6, '2021-07-25'),
    ( 2, 2, 17, 5, 7, '2020-12-06'),
    ( 28, 2, 8, 2, 8, '2021-01-23'),
    ( 1, 12, 13, 3, 9, '2019-03-17'),
    ( 38, 8, 1, 4, 10, '2021-10-05'),
    ( 21, 9, 12, 7, 11, '2023-04-12'),
    ( 35, 13, 2, 5, 12, '2022-05-30'),
    ( 11, 4, 15, 1, 13, '2020-10-18'),
    ( 29, 2, 13, 5, 14, '2022-02-25'),
    ( 15, 11, 5, 3, 15, '2019-12-03'),
    (22, 3, 19, 6, 1, '2021-11-30'),
    ( 30, 3, 14, 6, 12, '2022-03-15'),
    ( 33, 14, 12, 3, 1, '2021-08-30'),
    ( 44, 11, 1, 4, 14, '2021-04-26'),
    ( 7, 1, 2, 1, 10, '2022-12-12'),
    ( 25, 12, 6, 7, 2, '2020-07-09'),
    ( 49, 6, 7, 3, 1, '2021-03-04'),
    ( 41, 6, 3, 7, 2, '2020-01-16'),
    ( 27, 9, 20, 4, 2, '2021-01-07'),
    ( 6, 8, 18, 1, 14, '2023-02-20'),
    (42, 15, 20, 4, 6, '2022-06-03'),
    ( 26, 3, 2, 3, 8, '2021-06-21'),
    ( 10, 7, 9, 2, 8, '2020-04-29'),
    ( 43, 13, 16, 7, 5, '2021-07-08'),
    ( 14, 1, 4, 6, 8, '2020-08-27'),
    ( 50, 8, 7, 1, 11, '2022-08-05'),
    ( 36, 11, 20, 6, 12, '2021-05-12'),
    ( 39, 11, 3, 1, 12, '2020-12-21'),
    (4, 4, 16, 7, 4, '2020-09-01'),
    ( 16, 12, 10, 5, 3, '2021-10-17'),
    ( 20, 4, 15, 4, 4, '2022-04-05'),
    ( 32, 15, 6, 2, 7, '2022-01-13'),
    ( 24, 10, 1, 3, 7, '2022-07-29'),
    ( 3, 8, 12, 6, 8, '2020-11-10'),
    ( 37, 9, 13, 7, 3, '2021-09-14'),
    ( 48, 6, 16, 3, 7, '2021-12-28'),
    ( 18, 5, 17, 4, 15, '2020-05-31'),
    ( 45, 1, 5, 1, 13, '2021-02-16'),
    ( 46, 15, 20, 7, 10, '2023-01-28');


    INSERT INTO estudante (nome_estudante, data_nascimento, email_aluno, endereco_estudante, telefone_estudante, cpf_estudante, status)
VALUES
  ('João Silva', '1995-02-10', 'joao.silva@example.com', 'Rua A, 123', '(11) 987654321', '123.456.789-02', 'ativo');


INSERT INTO facilitador ( nome_facilitador, email_facilitador, data_nascimento, endereco_facilitador, cpf_facilitador)
VALUES
  ( 'Fernando Oliveira', 'fernando.oliveira@example.com', '1980-05-12', 'Rua A, 123', '070.670.980-01');


  INSERT INTO resilia (turma_id, modulo_id, curso_id, facilitador_id, data_registro)
VALUES
    ( 8, 10, 2, 15, '2022-09-18');



    INSERT INTO estudante (nome_estudante, data_nascimento, email_aluno, endereco_estudante, telefone_estudante, cpf_estudante, status)
VALUES
  ('João Silva', '1995-02-10', 'joao.silva@example.com', 'Rua A, 123', '(11) 987654321', '123.456.789-99', 'ativo');



UPDATE estudante SET status = 'ativo'
WHERE cpf_estudante = '123.456.789-99';



